# Generated by Django 4.2.1 on 2023-06-07 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='price',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='profile',
            name='profileimage',
            field=models.ImageField(default='profile2.avif', upload_to='profile/images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='pimage',
            field=models.ImageField(default='profile1.jpg', upload_to='profile/images'),
        ),
    ]
