# Generated by Django 4.2.1 on 2023-06-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_category_remove_profile_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pimage',
            field=models.ImageField(default='picture1.jpg', upload_to='profile/images'),
        ),
    ]
