# Generated by Django 4.2.1 on 2023-06-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_pimage_alter_profile_profileimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pimage',
            field=models.ImageField(default='/static/picture1.jpg', upload_to='profile/images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimage',
            field=models.ImageField(default='/static/profile2.avif', upload_to='profile/images'),
        ),
    ]
